// =============================================================
// ProductiveDay — Google Calendar Connect / Status button
// =============================================================

import { useState, useEffect } from "react";
import { CalendarDays, CheckCircle2, Loader2, Unlink } from "lucide-react";
import {
  getCalToken,
  connectGoogleCalendar,
  disconnectGoogleCalendar,
} from "@/lib/googleCalendar";

const CLIENT_ID = (import.meta as { env?: Record<string, string> }).env?.VITE_GOOGLE_CLIENT_ID ?? "";

interface Props {
  onConnected?: () => void;
  onDisconnected?: () => void;
}

export function GoogleCalendarSync({ onConnected, onDisconnected }: Props) {
  const [connected, setConnected]   = useState(false);
  const [loading, setLoading]       = useState(false);
  const [error, setError]           = useState<string | null>(null);
  const [showTip, setShowTip]       = useState(false);

  // Sync initial state
  useEffect(() => { setConnected(!!getCalToken()); }, []);

  // No Client ID configured → hide entirely
  if (!CLIENT_ID) return null;

  const connect = async () => {
    setLoading(true);
    setError(null);
    try {
      await connectGoogleCalendar(CLIENT_ID);
      setConnected(true);
      onConnected?.();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Connection failed");
    } finally {
      setLoading(false);
    }
  };

  const disconnect = () => {
    disconnectGoogleCalendar();
    setConnected(false);
    setShowTip(false);
    onDisconnected?.();
  };

  // ── Connected state ──────────────────────────────────────────
  if (connected) {
    return (
      <div className="relative">
        <button
          onClick={() => setShowTip((v) => !v)}
          className="flex items-center gap-1.5 text-[11px] font-medium text-emerald-600 dark:text-emerald-400
                     hover:text-emerald-700 dark:hover:text-emerald-300 transition select-none"
          title="Google Calendar connected"
        >
          <CheckCircle2 className="w-3.5 h-3.5" />
          <span className="hidden sm:inline">Calendar synced</span>
        </button>

        {showTip && (
          <div className="absolute right-0 top-8 z-50 bg-card border border-border/60 rounded-xl
                          shadow-lg p-3 w-52 animate-fade-in">
            <p className="text-[12px] text-foreground font-semibold mb-1">Google Calendar</p>
            <p className="text-[11px] text-muted-foreground leading-relaxed mb-3">
              Blocks are auto-synced when generated by AI. Completing a block marks it ✅ in your calendar.
            </p>
            <button
              onClick={disconnect}
              className="flex items-center gap-1.5 text-[11px] text-destructive/80
                         hover:text-destructive transition font-medium"
            >
              <Unlink className="w-3 h-3" />
              Disconnect calendar
            </button>
          </div>
        )}
      </div>
    );
  }

  // ── Disconnected state ───────────────────────────────────────
  return (
    <div>
      <button
        onClick={connect}
        disabled={loading}
        className="flex items-center gap-1.5 text-[11px] text-muted-foreground
                   border border-border/50 rounded-xl px-2.5 py-1
                   hover:bg-muted/50 hover:border-border hover:text-foreground
                   active:scale-95 transition-all select-none disabled:opacity-50"
        title="Connect Google Calendar"
      >
        {loading ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : (
          <CalendarDays className="w-3.5 h-3.5" />
        )}
        <span>{loading ? "Connecting…" : "Sync Calendar"}</span>
      </button>

      {error && (
        <p className="text-[10px] text-destructive mt-1 max-w-[180px] leading-tight">
          {error}
        </p>
      )}
    </div>
  );
}
